### ISSUE TITLE
Add to exclusions: sometimes does not add

### ISSUE THREAD

**Issue by grahamperrin** [claustromaniac/httpz#49] opened 2019-12-04 14:12 UTC
Sorry about this! 

Three frames from a screen recording: 

![2019-12-04 13:23:21 frame](https://user-images.githubusercontent.com/192271/70149384-dfe29100-169f-11ea-98c6-482bb45b7e1e.png)

![2019-12-04 13:23:26 frame](https://user-images.githubusercontent.com/192271/70149382-df49fa80-169f-11ea-9c36-b8817a5cdfde.png)

![2019-12-04 13:23:40 frame](https://user-images.githubusercontent.com/192271/70149380-df49fa80-169f-11ea-920c-bfc7dfcaf807.png)

Add, quit, start Firefox, view the list: no listing. 

I'm almost certain that it occurred on more than one occasion. 

<http://thegearcalculator.appspot.com/>

The recording: [2019-12-04 13:21.zip](https://github.com/claustromaniac/httpz/files/3922240/2019-12-04.13.21.zip)

IIRC my first realisation of the issue was when the secure page, which should have been excluded, was automatically loaded at Firefox start time (session restoration). 

Extension version 0.11.0b7

```text
grahamperrin@momh167-gjp4-8570p:~ % pkg query '%o %v %R' firefox
www/firefox 71.0_1,1 FreeBSD
grahamperrin@momh167-gjp4-8570p:~ % 
```

----

PS

> at Firefox start time (session restoration). 

– that's why I began this issue as separate from #42. For misbehaviour of *any* extension at session restoration, time I lazily think first of https://bugzilla.mozilla.org/show_bug.cgi?id=1378459 (i.e. not an issue with the extension) but on second thoughts, this issue is probably not 1378459. Sorry for rushing into this one.

**Comment by claustromaniac** [comment] 2019-12-04 15:02
Actually, this is intended behavior. Changes to exclusions made from the popup take from 10 to 60 seconds to get saved in the hard drive (almost always 10 seconds, and the variability is not random, but would take a while to explain it in english). This is to minimize writes, but I wouldn't mind changing that for the exclusions.

Changes to the other lists have similar delays, but I'd prefer not to touch those.

In case you're curious, the code responsible for these delays is here:

https://github.com/claustromaniac/httpz/blob/e2bb092e23bbef5f0487e52ac0bcb9d0d84ee1fc/src/bg/main.js#L3-L30

https://github.com/claustromaniac/httpz/blob/e2bb092e23bbef5f0487e52ac0bcb9d0d84ee1fc/src/bg/main.js#L59-L67

https://github.com/claustromaniac/httpz/blob/e2bb092e23bbef5f0487e52ac0bcb9d0d84ee1fc/src/bg/runtime.js#L3-L8

Another way to "solve" this would be to detect when Firefox is closing and always save the settings then, but that would not work if Firefox crashes, and I figured users wouldn't generally add something to the list of exclusions and close the browser less than 10 seconds afterwards anyway...

**Comment by grahamperrin** [comment] 2019-12-04 15:07
Thanks for the explanation. 

> I figured users wouldn't generally add something to the list of exclusions and close the browser less than 10 seconds afterwards anyway...

Yep.

**Comment by claustromaniac** [comment] 2019-12-04 15:35
Kudos for discovering this though. Good testing 😄

**Comment by claustromaniac** [comment] 2019-12-05 21:50
> Another way to "solve" this

Actually, if you close the browser less than 10 seconds after clicking the button in the popup, in that short time frame you probably don't even get to know whether you should exclude the site or not, in which case not saving that change is beneficial. 

Nothing to solve then.

<sub>Or maybe I'm just looking for a decent-sounding excuse to close this issue. 🙃 </sub>

**Closed as completed by claustromaniac** 2019-12-05 21:50 UTC
Labels: not an issue 😎
